


POST http://localhost:35000/register
Content-Type: application/json

{
    "username":"benz",
    "password":"1234"
}

#############
POST http://localhost:35000/login
Content-Type: application/json

{
    "username":"benz",
    "password":"1234"
}
##############
POST http://localhost:35000/auctionsstart
Content-Type: application/json

{
    "id_user": "Anuthep",
        "id_sell": "0",
        "price": 510
}